// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj9jwIsjlOGlR5T1uKVcUcadKcECTI8xA',
    appId: '1:919276666715:web:d4497c77722da81e77e47e',
    messagingSenderId: '919276666715',
    projectId: 'threads-clone-bhg',
    authDomain: 'threads-clone-bhg.firebaseapp.com',
    databaseURL: 'https://threads-clone-bhg-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'threads-clone-bhg.appspot.com',
    measurementId: 'G-F6VJB3XJ0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApbbvCpBXuqXbY-jJejxzXBp-H1640g-M',
    appId: '1:919276666715:android:3724a91abc8cd76277e47e',
    messagingSenderId: '919276666715',
    projectId: 'threads-clone-bhg',
    databaseURL: 'https://threads-clone-bhg-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'threads-clone-bhg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBphUBEWoNwGWuozQmPlkJMYEk9KcNN6J8',
    appId: '1:919276666715:ios:34fddb9fedffc6a777e47e',
    messagingSenderId: '919276666715',
    projectId: 'threads-clone-bhg',
    databaseURL: 'https://threads-clone-bhg-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'threads-clone-bhg.appspot.com',
    iosBundleId: 'com.example.flutterThreadClone',
  );
}
